"""empty message

Revision ID: 47f745bd236a
Revises: 96d12da86d63
Create Date: 2024-09-12 22:59:04.286858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47f745bd236a'
down_revision: Union[str, None] = '96d12da86d63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apiproduct', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.drop_column('purchase', 'max_uses')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('max_uses', sa.INTEGER(), nullable=True))
    op.drop_column('apiproduct', 'max_uses')
    # ### end Alembic commands ###
