"""empty message

Revision ID: 96d12da86d63
Revises: be966214e3e9
Create Date: 2024-09-12 22:44:08.540966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96d12da86d63'
down_revision: Union[str, None] = 'be966214e3e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('token', sa.String(), nullable=True))
    op.add_column('purchase', sa.Column('max_uses', sa.Integer(), nullable=True))
    op.add_column('purchase', sa.Column('uses', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'uses')
    op.drop_column('purchase', 'max_uses')
    op.drop_column('purchase', 'token')
    # ### end Alembic commands ###
