"""empty message

Revision ID: be966214e3e9
Revises: 408caba3b387
Create Date: 2024-09-12 18:33:42.808375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be966214e3e9'
down_revision: Union[str, None] = '408caba3b387'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apiproduct', sa.Column('is_private', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apiproduct', 'is_private')
    # ### end Alembic commands ###
